### ISSUE TITLE
如何测试

### ISSUE THREAD

**Issue by oldcatl** [KyanChen/FunSR#3]
你好，我需要在你提供的代码上直接测试运行我的数据集，我应该进行哪些修改？以方便我进行测试？

**Comment by KyanChen** [comment]
可以按readme进行数据准备，然后按3.1.2运行，直接进行测试

**Comment by oldcatl** [comment]
您好，我还是遇到了问题，我需要的是在我自己的数据集上，实现一个4倍超分辨率的效果，我应该如何操作才能获取到改模型的四倍超分辨率效果图？我实验的结果发现这个代码自己做了退化，然后恢复和/root/FunSR-cky/samples/UCMerced原输入分辨率一样的图片
















在 2023-05-28 11:06:42，"Keyan Chen" ***@***.***> 写道：

Closed #3 as completed.
